### ISSUE TITLE
How can I add a header to XHR before_handler?

### ISSUE THREAD

**Issue by Bodacious** [michelson/dante2#14]
In Rails, `protect_from_forgery with: :exception` expects there to be a `CSRF` meta tag content.

How can I configure this to be sent with the autosave post?

I've tried the following, but it doesn't work since there's no `xhr` argument for the before_handler callback

``` coffeescript
$data = $("[data-editor-content]").data()

    editor = new Dante
      el: "editor"
      read_only: !$data.editable
      content: $("[data-editor-content]").data("editor-content")
      upload_url: $data.uploadUrl
      data_storage:
        failure_handler: -> console.log("Failure")
        success_handler: -> console.log("Success")
        interval: 1000
        url: $data.dataStorageUrl
        method: "PATCH"
      xhr:
        before_handler: (xhr) ->
          console.log("This raises an exception")
```

**Comment by reimertz** [comment]
I added this feature on a local branch. Will create a PR soon, just need to write some tests.

**Comment by michelson** [comment]
@reimertz thanks! would be great to see that PR

**Comment by Bodacious** [comment]
@reimertz Did you finish this? It would be great if we could add this soon :)

**Comment by michelson** [comment]
Hi @Bodacious, we have released version 0.3.2, it will allow to pass headers as an option for `data_storage` config attribute. Also you can pass a `save_handler ` attr to `data_storage` in order to override the ajax behaviour with your own xhr implementation.

**Comment by Bodacious** [comment]
I've updated my gem to the current version, but still not seeing any headers when adding the headers option to `data_storage`

``` coffeescript
 $data = $("[data-editor-content]").data()

    editor = new Dante
      el: "editor"
      api_key: $data.apiKey
      read_only: !$data.editable
      content: $("[data-editor-content]").data("editor-content")
      upload_url: $data.uploadUrl
      data_storage:
        failure_handler: -> alert("Error saving post.")
        success_handler: -> notifyAutosave()
        interval: 2000
        url: $data.dataStorageUrl
        method: "PATCH"
        headers:
          FOO: "BAR"
```

Any suggestions?

**Comment by michelson** [comment]
make sure you are using 0.3.2 version.

I've tried to replicate you example:

results: 

![image](https://cloud.githubusercontent.com/assets/11976/23099287/b5d34458-f641-11e6-907d-828aa4cd9a53.png)

example: 

```js

  editor = new Dante(
    {
      api_key: "xxx",
      el: "editor",
      upload_url: uploadMethod,
      debug: #{Rails.env.production? ? false : true},
      read_only: false,
      data_storage: {
        url: saveUrl,
        method: saveMethod,
        success_handler: successStoreHandler,
        headers: {
                FOO: "BAR"
              }
      },
      xhr: {
        before_handler: handle_before_xhr_handler,
        success_handler: handle_success_xhr_handler
      },
      content: #{@post.serialized_content.blank? ? "''" : @post.serialized_content},
    }
  )
  editor.render()

```

**Comment by Mcastres** [comment]
I have the same configurations, but when I try to upload an Image headers are not sent
